### PR TITLE
changes to set the health monitor by name for the vip node

### PR DESCRIPTION
**Pull request by kumarappanc**
Fix to get the health monitors associated with the node

### CODE REVIEW

**Comment by tintoy** [comment]
I take it this was broken before?

**Comment by kumarappanc** [comment]
Yeah. Before it was not retrieving the health monitor details in the GetVipNode call

**Comment by tintoy** [comment]
Good catch! Thanks for fixing this :)

**Comment by tintoy** [comment]
Merged! You OK for me to delete the feature branch?

**Comment by kumarappanc** [comment]
Yeah.. You can delete it. Thanks

**Pull request merged**
